version: '3.3'
name: tapd-test-network
services:
  alice:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/lnd:v0.17.4-beta
    container_name: alice-lnd
    hostname: alice
    command: >-
      lnd --noseedbackup 
      --trickledelay=5000 
      --alias=alice 
      --externalip=alice
      --tlsextradomain=alice 
      --tlsextradomain=alice-lnd
      --listen=0.0.0.0:9735 
      --rpclisten=0.0.0.0:10009 
      --restlisten=0.0.0.0:8080
      --tlsautorefresh

      --bitcoin.node=neutrino
      --bitcoin.active
      --bitcoin.testnet

      --neutrino.addpeer=lnd.bitrefill.com
      --neutrino.addpeer=35.196.85.107
      --neutrino.addpeer=3.18.26.129
      --neutrino.addpeer=109.235.70.143
      --neutrino.addpeer=testnet1-btcd.zaphq.io
      --neutrino.addpeer=testnet2-btcd.zaphq.io
      --neutrino.addpeer=dev.conner.money

      --db.backend=postgres
      --db.postgres.dsn=postgres://postgres:postgrespwd@postgres-db:5432/alice_lnd

      --feeurl=https://assets.nostrassets.com/btc-testnet-fee-estimates.json
    restart: always
    volumes:
      - ./volumes/lnd/alice:/root/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '18080:8080'
      - '20009:10009'
      - '19735:9735'
  alice-tap: 
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/taproot-assets:v0.3.3
    container_name: alice-tap
    hostname: alice-tap
    command: >-
      tapd 
      --network=testnet 
      --debuglevel=debug 
      --tlsextradomain=alice-tap
      --tlsextradomain=alice-tap 
      --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 
      --lnd.host=alice-lnd:10009
      --lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
      --lnd.tlspath=/root/.lnd/tls.cert

      --databasebackend=postgres
      --postgres.host=postgres-db
      --postgres.port=5432
      --postgres.user=postgres
      --postgres.password=postgrespwd
      --postgres.dbname=alice_tapd
      --postgres.maxconnections=50

    restart: always
    volumes:
      - ./volumes/lnd/alice:/root/.lnd
      - ./volumes/tapd/alice:/root/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '18090:8089'
      - '20029:10029'
  bob:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/lnd:v0.17.4-beta
    container_name: bob-lnd
    hostname: bob
    command: >-
      lnd --noseedbackup 
      --trickledelay=5000 
      --alias=bob 
      --externalip=bob
      --tlsextradomain=bob 
      --tlsextradomain=bob-lnd
      --listen=0.0.0.0:9735 
      --rpclisten=0.0.0.0:10009 
      --restlisten=0.0.0.0:8080
      --tlsautorefresh

      --bitcoin.node=neutrino
      --bitcoin.active
      --bitcoin.testnet

      --neutrino.addpeer=lnd.bitrefill.com
      --neutrino.addpeer=35.196.85.107
      --neutrino.addpeer=3.18.26.129
      --neutrino.addpeer=109.235.70.143
      --neutrino.addpeer=testnet1-btcd.zaphq.io
      --neutrino.addpeer=testnet2-btcd.zaphq.io
      --neutrino.addpeer=dev.conner.money

      --db.backend=postgres
      --db.postgres.dsn=postgres://postgres:postgrespwd@postgres-db:5432/bob_lnd

      --feeurl=https://assets.nostrassets.com/btc-testnet-fee-estimates.json
    restart: always
    volumes:
      - ./volumes/lnd/bob:/root/.lnd
    expose:
      - '8080'
      - '10009'
      - '9735'
    ports:
      - '28080:8080'
      - '30009:10009'
      - '39735:9735'
  bob-tap:
    environment:
      USERID: ${USERID:-1000}
      GROUPID: ${GROUPID:-1000}
    stop_grace_period: 2m
    image: lightninglabs/taproot-assets:v0.3.3
    container_name: bob-tap
    hostname: bob-tap
    command: >-
      tapd 
      --network=testnet 
      --debuglevel=debug 
      --tlsextradomain=bob-tap
      --tlsextradomain=bob-tap 
      --rpclisten=0.0.0.0:10029
      --restlisten=0.0.0.0:8089 
      --lnd.host=bob-lnd:10009
      --lnd.macaroonpath=/root/.lnd/data/chain/bitcoin/testnet/admin.macaroon
      --lnd.tlspath=/root/.lnd/tls.cert
      
      --databasebackend=postgres
      --postgres.host=postgres-db
      --postgres.port=5432
      --postgres.user=postgres
      --postgres.password=postgrespwd
      --postgres.dbname=bob_tapd
      --postgres.maxconnections=50
    restart: always
    volumes:
      - ./volumes/lnd/bob:/root/.lnd
      - ./volumes/tapd/bob:/root/.tapd
    expose:
      - '8089'
      - '10029'
    ports:
      - '38089:8089'
      - '30029:10029'
  postgres:
    container_name: postgres-db
    hostname: postgres-db
    image: docker.io/bitnami/postgresql:14
    expose:
      - '5432'
    ports:
      - 35432:5432
    volumes:
      - ./volumes/postgres:/bitnami/postgresql
      - ./postgres.init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgrespwd
      - POSTGRESQL_DATABASE=postgres
